### ISSUE TITLE
Function_path editing 

### ISSUE THREAD

**Issue by lorenzoznerol** [KUL-Radneuron/KUL_VBG#1]
Dear developers, 

Congratulations for this pipeline!
I would like to use with my data. I tried with a subject (sub-01):
>> ./KUL_VBG.sh -p 01 -l $dir/KUL_VBG-master/lesion.nii.gz -z T1 -b -B1

This is my output:

Preproc_ dir is $dir/KUL_VBG-master/lesion_wf/proc_LWF/sub-01 and output dir is $dir/KUL_VBG-master/lesion_wf/output_LWF/sub-01
You are using KUL_VBG.sh version 0.47 - 02-01-2021
Inputs are -p  01  -lesion  $dir/KUL_VBG-master/lesion.nii.gz  -lesion_space  T1
 we have one session in the BIDS dir, this is good.
 We found T1 WIs $dir/KUL_VBG-master/BIDS/sub-01/sess1/anat/sub-01_T1w.nii.gz

 You have specified HD-BET for brain extraction, please make sure it is called correctly from within KUL_VBG
 In case of BET problems see lines 1124 - 1200 

update function path to reflect funciton name line 514

To solve this problem I changed the following: 
function_path=($(which KUL_VBG.sh | rev | cut -d"/" -f2- | rev))
to
function_path=($(which `pwd`/KUL_VBG.sh | rev | cut -d"/" -f2- | rev))

Could this edit modify the results?

Thanks a lot!
Lorenzo

**Comment by Rad-dude** [comment]
Dear Lorenzo,

Thanks for your interest in VBG.

For clarity, did VBG quit after printing this output? and is that why you modified line 514 accordingly?

function_path=($(which pwd/KUL_VBG.sh | rev | cut -d"/" -f2- | rev)) -> this line basically means that you have KUL_VBG.sh in the present working directory.

I would rather you install it somewhere and add it to your path, by adding something like this to your ~/.bashrc or ~/.bash_profile files:

# adding VBG to path
export PATH="/full_path_to_VBG/KUL_VBG-master/KUL_VBG:$PATH"

If you do the above and open up a new terminal, you should be able to find the script by simply typing KUL_V and hitting tab should autocomplete, no need for the preceding ./

I hope this helps.

Best,
AR

**Comment by lorenzoznerol** [comment]
Dear Rad, 

yes, I changed that line because VBG closed after that warning. After editing that line everything seems to work fine. 
Thanks for your time and your suggestion. 

Best,
Lorenzo

**Comment by Rad-dude** [comment]
Dear Lorenzo,

Glad to hear it's working.

I'll close this issue now, feel free to get back in touch with questions &/or feedback.

Best,
AR
