### ISSUE TITLE
Query regarding the lesion filled image

### ISSUE THREAD

**Issue by saruarlive** [KUL-Radneuron/KUL_VBG#11]
@KUL-Radneuron @Rad-dude Very interesting work. I have a query regarding the lesion filled [sub-JW001_T1_nat_filled_brain.nii.gz](https://github.com/KUL-Radneuron/KUL_VBG/files/8189580/sub-JW001_T1_nat_filled_brain.nii.gz) image. We can see large black regions in the image as attached here (a similar black region was detected when I ran 100+ subjects). Is it some sort of bug in the pipeline? Could you talk a bit more in regard!!!
<img width="205" alt="image" src="https://user-images.githubusercontent.com/24542592/167603413-b637ab16-6fae-47d3-9cd7-d221e2bbf195.png">
One more query is, should the lesion be connected for smooth lesion filling? Let's say a lesion has several connected components (4+) at both laterals (LT & RT). Will the lesion filling be smooth under the circumstances?

**Comment by KUL-Radneuron** [comment]
Hi Saruarlive,

Thanks for reaching out and sharing the filled image. It seems relatively okay to me, I understand that the intensity scaling is not perfect and this will be improved in the upcoming version (but I haven't had the time to work on that yet). These large black regions are typically CSF areas that get a lower than expected signal in the filled image. Are those areas also occurring in CSF spaces in the 100+ patients?

Did you have problems running FreeSurfer on this filled image or was that okay?

Regarding your second query, no actually you don't need to have a continuous lesion mask, the inpainting should work for multiple disconnected lesions (I had such a patient in the NIMG paper as well).

**Comment by saruarlive** [comment]
Hi, @KUL-Radneuron  @Rad-dude 
Thanks for your reply. No hard failures occurred in FreeSurfer parcellation. I have attached a GIF file for the visual inspection where the black regions are there. Looking forward to getting your comments in this regard.
![VBG_VisualInspect2](https://user-images.githubusercontent.com/24542592/168602501-46ba0428-12fb-47aa-8f68-3ce2455d4826.gif)

**Comment by KUL-Radneuron** [comment]
Hi @saruarlive,

Thanks for your reply and for providing the gif.

Okay glad to know that there were no hard failures for FS parcellation. 

This looks like a Sylvian fissure gone wrong, but I'm also wondering if these areas were actually excluded by HD-BET from the brain mask that it generated. 

Can you check the brain_mask_clean.nii.gz file to verify whether those areas were included in the brain mask or not? As VBG will limit the lesion inpainting normally to the voxels included in the brain mask only.

If this area is excluded by HD-BET then it might be helpful to try the workflow again by using ANTs-based brain extraction.

Best,
AR

**Comment by saruarlive** [comment]
Hi, @KUL-Radneuron @Rad-dude
Thanks for your reply. I think HD-BET is doing its job as we can see in the GIF file (*_Brain_clean_aff_2_temp_Warped.nii.gz is overlayed with *_Brain_clean_mask.nii.gz)
![VBG_VInspectV3](https://user-images.githubusercontent.com/24542592/168616010-1713b1ce-6c86-4821-99b1-47afb043dfee.gif)

**Comment by KUL-Radneuron** [comment]
Hi @saruarlive
Agreed, HD-BET seems to do just fine. I can only speculate without going through the intermediate files. If it's included in all subsequent brain masks, and covered by the combination of brain and lesion mask then it's more likely to be an in-painting error. 
Are those 2D T1s? Happy to give it a shot if you're fine with sharing the niftis, and can send you an upload link if so.

**Comment by saruarlive** [comment]
Thanks @KUL-Radneuron 
This is a 3D T1w image. I ask whether you are okay if I share through any private file sharing system you use in your institute (or any email ID to share).

**Comment by KUL-Radneuron** [comment]
Hi @saruarlive, I just emailed you a belnet file-share link (I used your gmail address on github), let me know how it goes, and feel free to email me at ahmed.radwan@kuleuven.be.
