### ISSUE TITLE
Execution time

### ISSUE THREAD

**Issue by TheoBiardeau** [KUL-Radneuron/KUL_VBG#12]
Hello,
I would like to know the approximate execution time for a 1*1*1 mm image in uVBG with a medium size tumor.
Best Theo

**Comment by KUL-Radneuron** [comment]
Hi Theo,

This largely depends on the resources available, with 20 cores or more it can be as quick as a few hours, the less cores you have the more it will take. Depending on the quality of the input image and and resulting filled image recon-all could be very quick (~2 hours) or can take its time for fixing any defects in the resulting surface (> 6 hours).

Best,
AR
