### ISSUE TITLE
MNI masks normalization 

### ISSUE THREAD

**Issue by lorenzoznerol** [KUL-Radneuron/KUL_VBG#2]
Dear  Ahmed

I'm using your code for brain tumor normalization to MNI with ANTs-BET for intra-axial lesions
>> ./KUL_VBG.sh -p subj001 -b -n 6 -l tumor_bin.nii.gz -z T1 -o subj001_norm -B 2

For every subject my segmentation mask have several values, ranging from 1 to 4. For the normalization I used the largest binary mask (voxels>1).

Results look fine. I guess that subj001_T1_brain_bk2anat1_Warped.nii.gz is my final normalized image, but there are several outputs and I'm quite confused how to normalize my original segmentation masks considering the different values.

Do you have any suggestions?
Thanks,
Lorenzo

**Comment by KUL-Radneuron** [comment]
Hi Lorenzo,

VBG's output should all be in native space, with native and standard orientation, but not normalized to MNI anymore. Images are warped to MNI space only for processing, then back to native for output.
The resulting warp and affine mat files should have MNI1 in their name (those should be in the intermediate processing folder) but you can probably achieve a better normalization if you run a new registration using the VBG filled images.

By normalization here do you mean getting the multi-label masks to a template space?
If so, you just need to use one of the warps to MNI.

Perhaps try with antsApplyTransforms using -n MultiLabel.
You can find example for using antsApplyTransforms here -> https://github.com/ANTsX/ANTs/issues/677

This should avoid aliasing the multiple labels in your lesion mask.

subj001_T1_brain_bk2anat1_Warped should actually be warped back to native space.

I hope this helps.

Best,
AR

**Comment by lorenzoznerol** [comment]
Dear Ahmed,

Thanks again for this clarification. 
I tried as you suggested starting from VBG filled images and everything works fine.

Cheers,
Lorenzo
